[project]
name = "api"
version = "0.1.0"
description = "The unified API for the Virion Labs platform."
authors = ["Virion Labs"]
license = "MIT"
requires-python = ">=3.11"
dependencies = [
    "fastapi>=0.111.0",
    "uvicorn[standard]>=0.30.0",
    "supabase>=2.5.0",
    "python-dotenv>=1.0.0"
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
