[project]
name = "api"
version = "0.1.0"
description = "The unified API for the Virion Labs platform."
authors = [{name = "Virion Labs", email = "engineering@virionlabs.com"}]
license = "MIT"
requires-python = ">=3.11"
dependencies = [
    "fastapi>=0.111.0",
    "uvicorn[standard]>=0.30.0",
    "supabase>=2.5.0",
    "python-dotenv>=1.0.0",
    "pydantic-settings>=2.0.0",
    "pydantic[email]>=2.0.0",
    "PyJWT>=2.8.0",
    "bcrypt>=4.0.1",
    "python-multipart>=0.0.6",
    "httpx>=0.27.0",
    "aiohttp>=3.9.0"
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"



[tool.hatch.build.targets.wheel]
include = [
    "main.py",
    "core/",
    "routers/",
    "services/",
    "schemas/",
    "generated_schemas/",
    "__init__.py"
]
