services:
  - type: web
    name: virion-labs-discord-bot-mvp
    runtime: node
    plan: free
    region: oregon
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 8080
      - key: DISCORD_BOT_TOKEN
        sync: false
      - key: BUSINESS_LOGIC_API_URL
        sync: false
      - key: API_KEY
        sync: false
      - key: DEBUG
        value: false